### ISSUE TITLE
Song skipping

### ISSUE THREAD

**Issue by Kahdeg-15520487** [akiroz/vplaylist#3]
https://akiroz.github.io/vplaylist/?v=PPeiRPLxkuE&s=3033#759478924718637066
after the above song is played, the next song also got skipped.

**Comment by akiroz** [comment]
Does it only happen with this specific one?

**Comment by Kahdeg-15520487** [comment]
i haven't encounter any other instance of this bug.

**Comment by akiroz** [comment]
Bug verified, Youtube's lib emitted the ended event 2 times. Possibly because the 2 tracks are on the same video and time ranges overlapped. I'm not sure if there's any ways to work around this bug.

**Comment by akiroz** [comment]
@Kahdeg-15520487 See commit for workaround ^
